// Code generated by protoc-gen-go. DO NOT EDIT.
// source: word.proto

package word

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_757f6f9a86a352a0, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type WordListResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 []*Word  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Extra                *Extra   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordListResponse) Reset()         { *m = WordListResponse{} }
func (m *WordListResponse) String() string { return proto.CompactTextString(m) }
func (*WordListResponse) ProtoMessage()    {}
func (*WordListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_757f6f9a86a352a0, []int{1}
}

func (m *WordListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordListResponse.Unmarshal(m, b)
}
func (m *WordListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordListResponse.Marshal(b, m, deterministic)
}
func (m *WordListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordListResponse.Merge(m, src)
}
func (m *WordListResponse) XXX_Size() int {
	return xxx_messageInfo_WordListResponse.Size(m)
}
func (m *WordListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WordListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WordListResponse proto.InternalMessageInfo

func (m *WordListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WordListResponse) GetData() []*Word {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WordListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WordListResponse) GetExtra() *Extra {
	if m != nil {
		return m.Extra
	}
	return nil
}

type Word struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Word                 string               `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	LastModifiedTime     *timestamp.Timestamp `protobuf:"bytes,5,opt,name=lastModifiedTime,proto3" json:"lastModifiedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_757f6f9a86a352a0, []int{2}
}

func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (m *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(m, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Word) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *Word) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *Word) GetLastModifiedTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifiedTime
	}
	return nil
}

type Extra struct {
	TotalCount           int64    `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Extra) Reset()         { *m = Extra{} }
func (m *Extra) String() string { return proto.CompactTextString(m) }
func (*Extra) ProtoMessage()    {}
func (*Extra) Descriptor() ([]byte, []int) {
	return fileDescriptor_757f6f9a86a352a0, []int{3}
}

func (m *Extra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extra.Unmarshal(m, b)
}
func (m *Extra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extra.Marshal(b, m, deterministic)
}
func (m *Extra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extra.Merge(m, src)
}
func (m *Extra) XXX_Size() int {
	return xxx_messageInfo_Extra.Size(m)
}
func (m *Extra) XXX_DiscardUnknown() {
	xxx_messageInfo_Extra.DiscardUnknown(m)
}

var xxx_messageInfo_Extra proto.InternalMessageInfo

func (m *Extra) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "word.ListRequest")
	proto.RegisterType((*WordListResponse)(nil), "word.WordListResponse")
	proto.RegisterType((*Word)(nil), "word.Word")
	proto.RegisterType((*Extra)(nil), "word.Extra")
}

func init() { proto.RegisterFile("word.proto", fileDescriptor_757f6f9a86a352a0) }

var fileDescriptor_757f6f9a86a352a0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4f, 0xe3, 0x30,
	0x10, 0x85, 0x37, 0x69, 0xd2, 0x55, 0x27, 0xda, 0x55, 0x77, 0xb4, 0xaa, 0xa2, 0x1e, 0x4a, 0xc8,
	0x85, 0x9c, 0x52, 0xa9, 0x3d, 0xc2, 0x09, 0x04, 0x27, 0xb8, 0x98, 0x4a, 0x9c, 0xdd, 0x7a, 0x52,
	0x59, 0x4a, 0xea, 0x12, 0xbb, 0xc0, 0x9d, 0x3f, 0xc4, 0x4f, 0x44, 0xb6, 0x13, 0x11, 0x89, 0x03,
	0xb7, 0x99, 0xe7, 0x99, 0xa7, 0xe7, 0x6f, 0x00, 0x5e, 0x55, 0x2b, 0xca, 0x63, 0xab, 0x8c, 0xc2,
	0xc8, 0xd6, 0xf3, 0xb3, 0xbd, 0x52, 0xfb, 0x9a, 0x96, 0x4e, 0xdb, 0x9e, 0xaa, 0xa5, 0x91, 0x0d,
	0x69, 0xc3, 0x9b, 0xa3, 0x1f, 0xcb, 0x2f, 0x21, 0xb9, 0x97, 0xda, 0x30, 0x7a, 0x3e, 0x91, 0x36,
	0x38, 0x83, 0xb1, 0xaa, 0x2a, 0x4d, 0x26, 0x0d, 0xb2, 0xa0, 0x18, 0xb1, 0xae, 0xc3, 0xff, 0x10,
	0xd7, 0xb2, 0x91, 0x26, 0x0d, 0x9d, 0xec, 0x9b, 0xfc, 0x3d, 0x80, 0xe9, 0x93, 0x6a, 0x85, 0x77,
	0xd0, 0x47, 0x75, 0xd0, 0x84, 0x08, 0xd1, 0x4e, 0x09, 0x72, 0x06, 0x7f, 0x98, 0xab, 0x71, 0x01,
	0x91, 0xe0, 0x86, 0xa7, 0x61, 0x36, 0x2a, 0x92, 0x15, 0x94, 0x2e, 0xa7, 0xdd, 0x64, 0x4e, 0xc7,
	0x14, 0x7e, 0x37, 0xa4, 0x35, 0xdf, 0x53, 0x3a, 0xca, 0x82, 0x62, 0xc2, 0xfa, 0x16, 0xcf, 0x21,
	0xa6, 0x37, 0xd3, 0xf2, 0x34, 0xca, 0x82, 0x22, 0x59, 0x25, 0x7e, 0xf5, 0xd6, 0x4a, 0xcc, 0xbf,
	0xe4, 0x1f, 0x01, 0x44, 0xd6, 0x0b, 0xff, 0x42, 0x28, 0x45, 0x17, 0x3c, 0x94, 0xc2, 0x26, 0xb1,
	0xd3, 0x2e, 0xf3, 0x84, 0xb9, 0x1a, 0xaf, 0x20, 0xd9, 0xb5, 0xc4, 0x0d, 0x89, 0x8d, 0x6c, 0xa8,
	0x73, 0x9d, 0x97, 0x1e, 0x53, 0xd9, 0x63, 0x2a, 0x37, 0x3d, 0x26, 0x36, 0x1c, 0xc7, 0x3b, 0x98,
	0xd6, 0x5c, 0x9b, 0x07, 0x25, 0x64, 0x25, 0x3b, 0x8b, 0xf8, 0x47, 0x8b, 0x6f, 0x3b, 0xf9, 0x05,
	0xc4, 0xee, 0x0b, 0xb8, 0x00, 0x30, 0xca, 0xf0, 0xfa, 0x46, 0x9d, 0x0e, 0x3d, 0xf3, 0x81, 0xb2,
	0xba, 0x86, 0xc4, 0x7e, 0xed, 0x91, 0xda, 0x17, 0xb9, 0x23, 0x5c, 0x43, 0x64, 0x59, 0xe3, 0x3f,
	0x8f, 0x61, 0x70, 0xb9, 0xf9, 0xec, 0x0b, 0xea, 0xf0, 0x1c, 0xf9, 0xaf, 0xed, 0xd8, 0x45, 0x5a,
	0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x46, 0xc9, 0x02, 0x1e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WordServiceClient is the client API for WordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WordServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*WordListResponse, error)
}

type wordServiceClient struct {
	cc *grpc.ClientConn
}

func NewWordServiceClient(cc *grpc.ClientConn) WordServiceClient {
	return &wordServiceClient{cc}
}

func (c *wordServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*WordListResponse, error) {
	out := new(WordListResponse)
	err := c.cc.Invoke(ctx, "/word.WordService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordServiceServer is the server API for WordService service.
type WordServiceServer interface {
	List(context.Context, *ListRequest) (*WordListResponse, error)
}

// UnimplementedWordServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWordServiceServer struct {
}

func (*UnimplementedWordServiceServer) List(ctx context.Context, req *ListRequest) (*WordListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterWordServiceServer(s *grpc.Server, srv WordServiceServer) {
	s.RegisterService(&_WordService_serviceDesc, srv)
}

func _WordService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/word.WordService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WordService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "word.WordService",
	HandlerType: (*WordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _WordService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "word.proto",
}
